function lambdafig(X1, Y1, M)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Nov-2010 18:21:29

% Create figure
figure1 = figure();

% Create axes
axes1 = axes('Parent',figure1,'FontSize',22,'FontName','Times New Roman');
box(axes1,'on');
%hold(axes1,'all');

% Create plot
plot(X1(1:M),Y1(1:M),'MarkerFaceColor',[0 0 0],'Marker','o');

% Create xlabel
xlabel('$\mathsf{M}$','Interpreter','latex','FontSize',22,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('$\lambda$','Interpreter','latex','FontSize',22,...
    'FontName','Times New Roman');

